//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.users = new HashSet<user>();
            this.locations = new HashSet<location>();
        }
    
        public int idCity { get; set; }
        public string name { get; set; }
        public string UF { get; set; }
    
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<location> locations { get; set; }
    }
}
