//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class like
    {
        public int idLike { get; set; }
        public bool like1 { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public bool diamond { get; set; }
        public int idUser { get; set; }
        public int idResidence { get; set; }
    
        public virtual residence residence { get; set; }
        public virtual user user { get; set; }
    }
}
