//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public location()
        {
            this.residences = new HashSet<residence>();
        }
    
        public int idLocation { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<int> idCity { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<residence> residences { get; set; }
    }
}
