//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class georentdbEntities : DbContext
    {
        public georentdbEntities()
            : base("name=georentdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<city> cities { get; set; }
        public DbSet<like> likes { get; set; }
        public DbSet<location> locations { get; set; }
        public DbSet<message> messages { get; set; }
        public DbSet<preference> preferences { get; set; }
        public DbSet<residence> residences { get; set; }
        public DbSet<residenceimage> residenceimages { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<userimage> userimages { get; set; }
    }
}
