//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class preference
    {
        public int idPreference { get; set; }
        public Nullable<bool> sponsor { get; set; }
        public Nullable<int> room { get; set; }
        public Nullable<int> bathroom { get; set; }
        public Nullable<int> vacancy { get; set; }
        public Nullable<bool> laundry { get; set; }
        public Nullable<decimal> income { get; set; }
        public Nullable<bool> condominium { get; set; }
        public Nullable<int> idResidence { get; set; }
        public Nullable<bool> child { get; set; }
        public Nullable<int> stay { get; set; }
        public Nullable<bool> pet { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual user user { get; set; }
    }
}
