//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class residence
    {
        public residence()
        {
            this.likes = new HashSet<like>();
            this.residenceimages = new HashSet<residenceimage>();
        }
    
        public int idResidence { get; set; }
        public int idLocator { get; set; }
        public int idResidencePref { get; set; }
        public int idLocation { get; set; }
        public int idUser { get; set; }
    
        public virtual ICollection<like> likes { get; set; }
        public virtual location location { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<residenceimage> residenceimages { get; set; }
    }
}
