//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class userimage
    {
        public int idUserImage { get; set; }
        public int idUser { get; set; }
        public string path { get; set; }
        public int resource { get; set; }
        public int order { get; set; }
    
        public virtual user user { get; set; }
    }
}
