//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoRentWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.likes = new HashSet<like>();
            this.messages = new HashSet<message>();
            this.messages1 = new HashSet<message>();
            this.preferences = new HashSet<preference>();
            this.residences = new HashSet<residence>();
            this.userimages = new HashSet<userimage>();
        }
    
        public int idUser { get; set; }
        public string name { get; set; }
        public System.DateTime birthDate { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public decimal credits { get; set; }
        public int idCity { get; set; }
        public int type { get; set; }
        public int range { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<like> likes { get; set; }
        public virtual ICollection<message> messages { get; set; }
        public virtual ICollection<message> messages1 { get; set; }
        public virtual ICollection<preference> preferences { get; set; }
        public virtual ICollection<residence> residences { get; set; }
        public virtual ICollection<userimage> userimages { get; set; }
    }
}
